value_ch1 = adc.read_adc(1, gain=GAIN)
value_ch2 = adc.read_adc(2, gain=GAIN)
value_ch3 = adc.read_adc(3, gain=GAIN)
print(f'Channel 1: {value_ch1}')
print(f'Channel 2: {value_ch2}')
print(f'Channel 3: {value_ch3}')
